### ISSUE TITLE
Multi inventory

### ISSUE THREAD

**Issue by xipanca** [vatto1337/react-game-inventory-dnd#1]
What would it be like if I had to move from inventory to another? Example inventory for the trunk

**Comment by vatto1337** [comment]
Just re-use the CSS & HTML and and to every item something that differentiate what "inventory" they're from. For example in my case I added something called "storeId" 


so if an item has storeId = "vehicle" => is part of the vehicle's inventory.

if an item has storeId = "player" - Is part of the player's inventory
